// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOsDemo
{
	public partial class AddressBookViewCon : UIViewController
	{
		public AddressBookViewCon (IntPtr handle) : base (handle)
		{
		}
	}
}
